[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/src/",
    "@uniswap/v4-periphery/=lib/v4-periphery/src/",
    "@uniswap/universal-router/=lib/universal-router/contracts/",
    "permit2/=lib/permit2/src/"
]
# solc_version auto-detect (usa 0.8.30 local)
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"
ignored_error_codes = [2018, 5574]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
